ALTER TABLE montant
  MODIFY COLUMN type_paiement ENUM(
    'FRAIS_PREINSCRIPTION',
    'FRAIS_INSCRIPTION',
    'FRAIS_SCOLAIRE',
    'FRAIS_TRANSPORT',
    'FRAIS_CANTINE',
    'FRAIS_EXAMEN',
    'FRAIS_MATIERES',
    'FRAIS_MATERIEL',
    'FRAIS_UNIFORME',
    'FRAIS_ASSURANCE',
    'FRAIS_BIBLIOTHEQUE',
    'FRAIS_ACTIVITE',
    'FRAIS_PHOTO',
    'FRAIS_AUTRES',
    'SOUTIEN_PSYCHOLOGIQUE',
    'SOUTIEN_MEDICAL',
    'SOUTIEN_SOCIAL',
    'SOUTIEN_JURIDIQUE',
    'SOUTIEN_TECHNIQUE',
    'SOUTIEN_ADMINISTRATIF'
  ) NOT NULL;

ALTER TABLE paiements
  MODIFY COLUMN Type_paiement ENUM(
    'FRAIS_PREINSCRIPTION',
    'FRAIS_INSCRIPTION',
    'FRAIS_SCOLAIRE',
    'FRAIS_TRANSPORT',
    'FRAIS_CANTINE',
    'FRAIS_EXAMEN',
    'FRAIS_MATIERES',
    'FRAIS_MATERIEL',
    'FRAIS_UNIFORME',
    'FRAIS_ASSURANCE',
    'FRAIS_BIBLIOTHEQUE',
    'FRAIS_ACTIVITE',
    'FRAIS_PHOTO',
    'FRAIS_AUTRES',
    'SOUTIEN_PSYCHOLOGIQUE',
    'SOUTIEN_MEDICAL',
    'SOUTIEN_SOCIAL',
    'SOUTIEN_JURIDIQUE',
    'SOUTIEN_TECHNIQUE',
    'SOUTIEN_ADMINISTRATIF'
  ) NOT NULL;

UPDATE montant
SET type_paiement = 'FRAIS_PREINSCRIPTION'
WHERE type_paiement = 'FRAIS_INSCRIPTION';
