CREATE TABLE IF NOT EXISTS app_preferences (
  id BIGINT NOT NULL,
  school_name VARCHAR(160) NOT NULL,
  school_code VARCHAR(50),
  school_email VARCHAR(150) NOT NULL,
  school_phone VARCHAR(40),
  school_website VARCHAR(200),
  school_address VARCHAR(255),
  language VARCHAR(10) NOT NULL,
  timezone VARCHAR(80) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  date_format VARCHAR(20) NOT NULL,
  time_format VARCHAR(5) NOT NULL,
  theme VARCHAR(20) NOT NULL,
  start_of_week VARCHAR(20) NOT NULL,
  page_size INT NOT NULL,
  notify_email BOOLEAN NOT NULL,
  notify_sms BOOLEAN NOT NULL,
  notify_absence BOOLEAN NOT NULL,
  notify_grades BOOLEAN NOT NULL,
  require_two_factor BOOLEAN NOT NULL,
  session_timeout_minutes INT NOT NULL,
  password_min_length INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS support_ticket (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL,
  subject VARCHAR(160) NOT NULL,
  message VARCHAR(2000) NOT NULL,
  priority VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  INDEX idx_support_ticket_email (email),
  INDEX idx_support_ticket_status (status),
  INDEX idx_support_ticket_created_at (created_at)
);
